# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeHeadStart' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeHeadStart

  target 'ReactNativeHeadStartTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeHeadStart-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeHeadStart-tvOS

  target 'ReactNativeHeadStart-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
